plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - '.git/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'

# Style configurations
Style/Documentation:
  Enabled: false

# Metrics configurations
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

# Rails configurations
Rails:
  Enabled: true
